# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Item

# Model Form Field configuration
form: $/polilla/demo/models/item/fields.yaml

# Model Class name
modelClass: Polilla\Demo\Models\Item

# Default redirect location
defaultRedirect: polilla/demo/items

# Create page
create:
    title: backend::lang.form.create_title
    redirect: polilla/demo/items/update/:id
    redirectClose: polilla/demo/items

# Update page
update:
    title: backend::lang.form.update_title
    redirect: polilla/demo/items
    redirectClose: polilla/demo/items

# Preview page
preview:
    title: backend::lang.form.preview_title
